### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by maxx203** [firehol/blocklist-ipsets#267]
Hi 

any feedback yet when lists are getting updated?
Or does anyone found new IP lists?

Kind regards
Maxx

**Comment by Belgarion** [comment]
Unfortunately this repo seems to be abandoned.

**Comment by mai1x9** [comment]
> Unfortunately this repo seems to be abandoned.

Hello there, what does that mean, isn't this repo maintained no longer. I could see the repo os updated if not very often atleast a week or so.

**Comment by alyandon** [comment]
I guess it is time to start looking for alternatives?  I haven't had too much luck so far.  :(

**Comment by maxx203** [comment]
I just found that https://iplists.firehol.org/# has updated lists. For some reason they are not on github anymore. But the lists on the website directly are getting updated. Use the file behind the "local copy" donwload and you change the URL in the conf file.

**Comment by Belgarion** [comment]
Far from all lists on https://iplists.firehol.org are updating properly. 

The following have fetch errors since the letsencrypt root expiration back in 2021 ( https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/ ):

* bruteforceblocker
* cidr_report_bogons
* dataplane_*
* sblam
* tor_exits
* turris_greylist
* yoyo_adservers

**Comment by maxx203** [comment]
At least some. For me the spam stopped and iam most likely good to go.
