### ISSUE TITLE
Android mobiles

### ISSUE THREAD

**Issue by shaiderer** [firehol/blocklist-ipsets#27]
Hello!

I want to use firehol with pfsense at home. When I add the list to my ipv4 tab with deny both, my android devices are not able to use the wifi anymore.

any ideas here?
thanks

**Comment by ktsaou** [comment]
I guess you mean `firehol_level1`, because firehol is a Linux firewall and cannot be used with pfsense.

Well... `firehol_level1` includes by definition all the private IP address space, so no private IPs will be allowed. The right way to use it, it to apply it at the internet facing side of your firewall.

Unfortunately, I don't use pfsense, so I don't know how to do this with pfsense.

**Comment by shaiderer** [comment]
Hello!

OK, my issue is that I have used that for WAN and LAN as well.
When the list contains internal IP/subnet as well, it s clear that this will not work


thanks

**Comment by ktsaou** [comment]
ok, nice. I am closing this.
