### ISSUE TITLE
Blocking 8.8.8.8

### ISSUE THREAD

**Issue by nomadturk** [firehol/blocklist-ipsets#45]
Well,

Your lists started blocking 8.8.8.8
After a quick check-up, turns out you guys are blocking google DNS due to some hphosts entries.
Since the list maintainer does only domain based lists, I'ld say this is on you. (:

**Comment by ktsaou** [comment]
Hi,

let's see:

```sh
# echo "8.8.8.8" | iprange - --compare-next *.{ip,net}set | grep -v ",0$"
stdin,firehol_webserver.netset,1,66531,1,34744374,34744374,1
stdin,packetmail_emerging_ips.ipset,1,25,1,25,25,1
stdin,hphosts_psh.ipset,1,33881,1,33881,33881,1
stdin,hphosts_fsa.ipset,1,27070,1,27070,27070,1
stdin,hphosts_emd.ipset,1,28022,1,28022,28022,1
```

hm...

```sh
# cat hphosts_emd.source | cut -f 2 | iprange -v --dns-threads 300 2>&1 | grep "8\.8\.8\.8"
iprange: DNS: 'sexy.f3322.org' = 8.8.8.8
iprange: DNS: 'seo777.f3322.net' = 8.8.8.8

# cat hphosts_fsa.source | cut -f 2 | iprange -v --dns-threads 300 2>&1 | grep "8\.8\.8\.8"
iprange: DNS: 'www.microsoftkeysstore.com' = 8.8.8.8

```

So, there are a few domains resolving to this IP.

I think hphosts lists are prone to this kind of poisoning. The domain owners can list any IP they like.

So, it should probably be best to remove them from `firehol_webserver`.
Making a PR now.

**Comment by ktsaou** [comment]
merged it.
Thank you for reporting it.
The site will be updated in a while.

**Comment by ktsaou** [comment]
updated the site too: https://iplists.firehol.org/?ipset=firehol_webserver

**Comment by l1kw1d** [comment]
@ktsaou Many private and some public networks generate PTR (reverse lookup) queries for RFC 1918 addresses, dynamic DNS updates and other ambiguous addresses.
This happens because many of the same people running those networks neglect to run a DNS server of their own, or worse, simply don't enumerate their IP address use in both forward and reverse DNS zones. This creates many queries which are ultimately sent up to the root DNS server system which in turn responds with negative answers. You should look at https://www.as112.net/ops-listing.html .
