### ISSUE TITLE
There are no new commits in master branch

### ISSUE THREAD

**Issue by spacepatcher** [firehol/blocklist-ipsets#51]
Hello!
I use your wonderful repository to get processed reputation lists. But recently the process of updating the repository (master branch) has stopped. Is it due to some technical problems?

Thanks!

**Comment by spacepatcher** [comment]
Update.
Please pay your attention.

**Comment by kylemanna** [comment]
[Indeed.](https://github.com/firehol/blocklist-ipsets/commits/master)

**Comment by ktsaou** [comment]
Hi,

Due to rate of changes to these files, github demanded to update this repo once per day at most.

The site provides links to all files for real-time updates, hosted at a web server outside github.

So, unfortunately we lost the ability to track changes.

**Comment by ktsaou** [comment]
I forgot to mention that also github detached all forks from the repo.

Generally, there is no history on this repo. We commit once per day, and each commit overwrites everything - like starting the repo from scratch.

github insisted to have it like that, because it required a tremendous amount of resources from them to maintain a network of forks for this repo.

**Comment by ktsaou** [comment]
and now I see we are updating the main repo daily. only gh-pages.
let me fix that.

**Comment by spacepatcher** [comment]
@ktsaou, 
thanks a lot!

**Comment by ktsaou** [comment]
ok, fixed it.
Somehow it corrupted the local git copy and then failed to push it.

**Comment by spacepatcher** [comment]
@ktsaou,
I don't see any updates in master branch since 20.12.2017. Is it due to the same problem with local git copy?

Thanks!

**Comment by ktsaou** [comment]
fixed it once more.
for some reason, git refused to push it.
I think I fixed it now.
